name: msi_parcel_customer
description: MSI Parcel - send parcels, track live, pay with wallet.
publish_to: 'none'
version: 0.2.0+2

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  url_launcher: ^6.3.0
  geolocator: ^13.0.1
  flutter_map: '>=7.0.2 <9.0.0'
  latlong2: ^0.9.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/msi_parcel_logo.png
